name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'

            cd /home/${{ secrets.VM_USER }}

            if [ ! -d "ml-detection-intrusions/.git" ]; then
              git clone https://github.com/sadiya1804/ml-detection-intrusions.git
            fi

            cd ml-detection-intrusions
            git checkout main
            git pull origin main

            docker compose down
            docker compose up -d --build

          EOF
